CREATE TABLE tb_persons (
    idperson INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    lastName VARCHAR(30) NOT NULL,
    email VARCHAR(128) UNIQUE DEFAULT NULL ,
    gender TINYINT NOT NULL,
    dtregister timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);