# Generated by Django 4.2.2 on 2023-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), (None, "Not Specified")],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
    ]
