# Generated by Django 4.2.2 on 2023-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_alter_usergithub_bio_alter_usergithub_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergithub",
            name="blog",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
