# Generated by Django 4.2.2 on 2023-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0013_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image_url",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
