# Generated by Django 4.2.2 on 2023-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0014_alter_user_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
